export const countyOptions = [
  // Romania
  { label: "Alba", value: "RO-AB" },
  { label: "Argeș", value: "RO-AG" },
  { label: "Arad", value: "RO-AR" },
  { label: "Bacău", value: "RO-BC" },
  { label: "Bihor", value: "RO-BH" },
  { label: "Bistrița-Năsăud", value: "RO-BN" },
  { label: "Brăila", value: "RO-BR" },
  { label: "Botoșani", value: "RO-BT" },
  { label: "București", value: "RO-B" },
  { label: "Brașov", value: "RO-BV" },
  { label: "Buzău", value: "RO-BZ" },
  { label: "Cluj", value: "RO-CJ" },
  { label: "Călărași", value: "RO-CL" },
  { label: "Caraș-Severin", value: "RO-CS" },
  { label: "Constanța", value: "RO-CT" },
  { label: "Covasna", value: "RO-CV" },
  { label: "Dâmbovița", value: "RO-DB" },
  { label: "Dolj", value: "RO-DJ" },
  { label: "Gorj", value: "RO-GJ" },
  { label: "Galați", value: "RO-GL" },
  { label: "Giurgiu", value: "RO-GR" },
  { label: "Hunedoara", value: "RO-HD" },
  { label: "Harghita", value: "RO-HR" },
  { label: "Ilfov", value: "RO-IF" },
  { label: "Ialomița", value: "RO-IL" },
  { label: "Iași", value: "RO-IS" },
  { label: "Mehedinți", value: "RO-MH" },
  { label: "Maramureș", value: "RO-MM" },
  { label: "Mureș", value: "RO-MS" },
  { label: "Neamț", value: "RO-NT" },
  { label: "Olt", value: "RO-OT" },
  { label: "Prahova", value: "RO-PH" },
  { label: "Sibiu", value: "RO-SB" },
  { label: "Sálaj", value: "RO-SJ" },
  { label: "Satu Mare", value: "RO-SM" },
  { label: "Suceava", value: "RO-SV" },
  { label: "Tulcea", value: "RO-TL" },
  { label: "Timiș", value: "RO-TM" },
  { label: "Teleorman", value: "RO-TR" },
  { label: "Vâlcea", value: "RO-VL" },
  { label: "Vrancea", value: "RO-VN" },
  { label: "Vaslui", value: "RO-VS" },

  // Serbia
  { label: "Beograd", value: "RS-00" },
  { label: "Severnobački okrug", value: "RS-01" },
  { label: "Srednjebanatski okrug", value: "RS-02" },
  { label: "Severnobanatski okrug", value: "RS-03" },
  { label: "Južnobanatski okrug", value: "RS-04" },
  { label: "Zapadnobački okrug", value: "RS-05" },
  { label: "Južnobački okrug", value: "RS-06" },
  { label: "Sremski okrug", value: "RS-07" },
  { label: "Mačvanski okrug", value: "RS-08" },
  { label: "Kolubarski okrug", value: "RS-09" },
  { label: "Podunavski okrug", value: "RS-10" },
  { label: "Braničevski okrug", value: "RS-11" },
  { label: "Šumadijski okrug", value: "RS-12" },
  { label: "Pomoravski okrug", value: "RS-13" },
  { label: "Borski okrug", value: "RS-14" },
  { label: "Zaječarski okrug", value: "RS-15" },
  { label: "Zlatiborski okrug", value: "RS-16" },
  { label: "Moravički okrug", value: "RS-17" },
  { label: "Raški okrug", value: "RS-18" },
  { label: "Rasinski okrug", value: "RS-19" },
  { label: "Nišavski okrug", value: "RS-20" },
  { label: "Toplički okrug", value: "RS-21" },
  { label: "Pirotski okrug", value: "RS-22" },
  { label: "Jablanički okrug", value: "RS-23" },
  { label: "Pčinjski okrug", value: "RS-24" },

  // Ukraine
  { label: "Chernihiv Oblast", value: "chernihiv" },
  { label: "Volyn Oblast", value: "volyn" },
  { label: "Rivne Oblast", value: "rivne" },
  { label: "Zhytomyr Oblast", value: "zhytomyr" },
  { label: "Kiev", value: "kiev" },
  { label: "Kiev city", value: "kiev_city" },
  { label: "Zakarpattia Oblast", value: "zakarpattia" },
  { label: "Chernivtsi Oblast", value: "chernivtsi" },
  { label: "Ivano-Frankivsk Oblast", value: "ivano-frankivsk" },
  { label: "Odessa Oblast", value: "odessa" },
  { label: "Vinnytsia Oblast", value: "vinnytsia" },
  { label: "Lviv Oblast", value: "lviv" },
  { label: "Sumy Oblast", value: "sumy" },
  { label: "Kharkiv Oblast", value: "kharkiv" },
  { label: "Luhansk Oblast", value: "luhansk" },
  { label: "Donetsk Oblast", value: "donetsk" },
  { label: "Kherson Oblast", value: "kherson" },
  { label: "Zaporizhzhya Oblast", value: "zaporizhzhya" },
  { label: "Mykolaiv Oblast", value: "mykolayiv" },
  { label: "Poltava Oblast", value: "poltava" },
  { label: "Khmelnytsky Oblast", value: "khmelnytsky" },
  { label: "Ternopil Oblast", value: "ternopil" },
  { label: "Dnipropetrovsk Oblast", value: "dnipropetrovsk" },
  { label: "Cherkasy Oblast", value: "cherkasy" },
  { label: "Kirovohrad Oblast", value: "kirovohrad" },

  // Slovakia
  { label: "Žilinský kraj", value: "SKZI" },
  { label: "Prešov", value: "SKPV" },
  { label: "Košický kraj", value: "SKKI" },
  { label: "Bratislavský", value: "SKBL" },
  { label: "Trnavský", value: "SKTA" },
  { label: "Trenciansky", value: "SKTC" },
  { label: "Banskobystrický", value: "SKBC" },
  { label: "Nitriansky", value: "SKNI" },

  // Hungary
  { label: "Bács-Kiskun", value: "HU-BK" },
  { label: "Baranya", value: "HU-BA" },
  { label: "Békés", value: "HU-BE" },
  { label: "Békéscsaba", value: "HU-BC" },
  { label: "Borsod-Abaúj-Zemplén", value: "HU-BZ" },
  { label: "Budapest", value: "HU-BU" },
  { label: "Csongrád-Csanád", value: "HU-CS" },
  { label: "Debrecen", value: "HU-DE" },
  { label: "Dunaújváros", value: "HU-DU" },
  { label: "Eger", value: "HU-EG" },
  { label: "Fejér", value: "HU-FE" },
  { label: "Győr", value: "HU-GY" },
  { label: "Győr-Moson-Sopron", value: "HU-GS" },
  { label: "Hajdú-Bihar", value: "HU-HB" },
  { label: "Heves", value: "HU-HE" },
  { label: "Hódmezővásárhely", value: "HU-HV" },
  { label: "Jász-Nagykun-Szolnok", value: "HU-JN" },
  { label: "Kaposvár", value: "HU-KV" },
  { label: "Kecskemét", value: "HU-KM" },
  { label: "Komárom-Esztergom", value: "HU-KE" },
  { label: "Miskolc", value: "HU-MI" },
  { label: "Nagykanizsa", value: "HU-NK" },
  { label: "Nógrád", value: "HU-NO" },
  { label: "Nyíregyháza", value: "HU-NY" },
  { label: "Pécs", value: "HU-PS" },
  { label: "Pest", value: "HU-PE" },
  { label: "Somogy", value: "HU-SO" },
  { label: "Sopron", value: "HU-SN" },
  { label: "Szabolcs-Szatmár-Bereg", value: "HU-SZ" },
  { label: "Szeged", value: "HU-SD" },
  { label: "Székesfehérvár", value: "HU-SF" },
  { label: "Szolnok", value: "HU-SK" },
  { label: "Szombathely", value: "HU-SH" },
  { label: "Tatabánya", value: "HU-TB" },
  { label: "Tolna", value: "HU-TO" },
  { label: "Vas", value: "HU-VA" },
  { label: "Veszprém", value: "HU-VE" },
  { label: "Veszprém (megye)", value: "HU-VM" },
  { label: "Zala", value: "HU-ZA" },
  { label: "Zalaegerszeg", value: "HU-ZE" },
];
